### Build ###
FROM node:10.9.0 as build

WORKDIR /usr/src/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --output-path=dist
# CMD ["npm", "run", "build"]


### PROD ###
FROM nginx:1.16.0-alpine

# copy artifact build from the 'build environment'
COPY --from=build /usr/src/app/dist/blogshop-app /usr/share/nginx/html
# copy nginx config file
COPY --from=build /usr/src/app/nginx-custom.conf /etc/nginx/conf.d/default.conf

# Just checking if my files are there.
RUN ls /usr/share/nginx/html
# expose port
EXPOSE 80

